# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src;/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/build_spades")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Unspecified;runtime")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "TBZ2")
set(CPACK_IGNORE_FILES "tools;test;web_service;online_vis;cap")
set(CPACK_INSTALLED_DIRECTORIES "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne")
set(CPACK_MODULE_PATH "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src/cmake;/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "SPAdes 3.12.0-dev")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "SPAdes 3.12.0-dev")
set(CPACK_OUTPUT_CONFIG_FILE "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/build_spades/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src/../README")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Project built using CMake")
set(CPACK_PACKAGE_FILE_NAME "SPAdes-3.12.0-dev")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "SPAdes 3.12.0-dev")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "SPAdes 3.12.0-dev")
set(CPACK_PACKAGE_NAME "SPAdes")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Saint Petersburg State University")
set(CPACK_PACKAGE_VERSION "3.12.0-dev")
set(CPACK_PACKAGE_VERSION_MAJOR "3")
set(CPACK_PACKAGE_VERSION_MINOR "12")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src/../LICENSE")
set(CPACK_RESOURCE_FILE_README "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.11.2-llxe55ngixw3ooatarjc66thfg57csn5/share/cmake-3.11/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.11.2-llxe55ngixw3ooatarjc66thfg57csn5/share/cmake-3.11/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2")
set(CPACK_SOURCE_IGNORE_FILES "tools;test;web_service;online_vis;cap")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/src;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/build_spades/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "SPAdes-3.12.0-dev")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/lam4003/bin/linked_read_deconvolution/workflow/ext/ariadne/build_spades/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
